# Connexion à ta base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sae_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port du serveur (8080 par défaut)
server.port=8080